version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_fastapi_db 
    ports: 
      - 6379:6379
    command: ["redis-server","--appendonly","yes"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081

    depends_on:
      - redis


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    command: "--config.file=/etc/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports: 
      - 3000:3000

  